### ISSUE TITLE
Remove tvaddons.nl 

### ISSUE THREAD

**Issue by kodidev** [XvBMC/repository.xvbmc#101]
Graag de repo tvaddons.nl verwijderen. 
Tenzij de originele hier geplaatst wordt. Wij zorgen er voor dat de misstap van rob niet wederom gedaan wordt.
Laten we met zijn allen 1 mooi kodi systeem maken en geen ruzies uitvechten over de ruggen van gebruikers.

**Comment by EPiC-APOC** [comment]
**Akkoord**, _hopelijk kunnen we het leuk houden voortaan en bind vooral Rob zich serieus in want wij zijn z'n kunstjes en hetze méér dan spuugzat namelijk..._

Groeten team XvBMC Nederland, 
_(xbmc nl)_

**Comment by misa2610** [comment]
:).....als onder hetze verstaan wordt gebruikers adviseren om systemen op te bouwen middels originele source > Repo > addon zie ik daar niets verkeerds aan. Gebruiker bepaalt uiteindelijk altijd zelf wat er op zijn/haar systeem komt te staan uiteraard. Succes verder met de repo.

**Comment by EPiC-APOC** [comment]
**Hou toch op man**, met je anti XvBMC (onder andere) en gezeik over addons van ons èn dat deze zouden bijten. Je weet niet waar je over praat man, klein voorbeeldje, HD/RD lite bijt met HELEMAAL NIKS... uitvoerig getest en kon zonder welk probleem dan ook keurig netjes naast de originele Salts.
Ook staat keurig in die addons vermeld dat het een #MOD betreft plus de credit naar de oorspronkelijke #Dev #TKnorris. 
 
EN wie gapt er overigens addons dan? JIJ toch Rob met je dutchdream wat volledige kopie is van onze NL viewer en komt er v2 en prompt daar is v2 van dutchdream, opensource gezeik moet je niet mee aankomen, jij doet net of het jouw geweldige idee en werk is, daar zit de kneep, beetje vent vermeld erbij eerst en duidelijk bij dat je een twist aan de XvBMC addon 'NL viewer' door Scott Marten (in correcte spelling) heb gegeven voor je dutchdream. 
 
Wie knalt er fake/kapotte addons in TVaddons.nl repo?
Promote je die zelfde addon later wel loop je te zeiken over teveel Python etc. 
Werkelijk te sneu, wat is die toegevoegde waarde, iemand doet zijn best voor iets wat gewoon wel leuk werkt maar dan ga je er nog semi negatief over lopen doen... en zo kunnen we nogal even doorgaan over héél wat andere akkefietjes nog. 
Waarbij al ik weet niet hoe lang jij alleen maar publiekelijk overal zuur loopt te doen over en jegens ons, iets met afgunst of zo toevallig? OF heb je een minderwaardigheidscomplex? 
 
Zo weten we nogal wat zwakke (publieke) pogingen om 'Q' zwart te maken ed. etc.
 
Nog zo'n simpel voorbeeldje is dat alle beheerders van XvBMC automatisch werden geblocked, zo ook nieuwe beheerders die lid waren van een bepaalde FB-pagina zonder ooit problemen hadden gegeven en ineens uit het niks een block kregen puur omdat ze beheerder waren geworden bij XvBMC, dan praten we al over heel lang geleden dus kom niet met recent gelul aan.
 
Maar goed het lijstje is nog wel langer dan dit en veranderd niks aan de situatie, wij zijn er in elk geval klaar mee, als je je gewoon eens met jezelf zou bemoeiën dat zou een hele wereld schelen en ben je al druk zat volgens mij. Hebben wij ook geen last van jou, heb jij geen last van ons, man wij lopen toch ook niet overal publiekelijk te huilen over jou, wat voor zielig Calimero gedrag is dat man???
 
Bedankt voor deze gratis therapie sessie, lucht op, hopelijk leer je je grote mond eens houden en kunnen we rustig naast elkaar bestaan zonder irritatie over en weer. Als jij je mond over ons houdt hoeven wij ons niet onnodig te irriteren. Vrij simpel toch?
 
Goed weekend

**Comment by misa2610** [comment]
Bedankt voor de opbouwende kritiek daar kan ik tenminste wat mee. Bij deze excuses voor de irritatie die blijkbaar is veroorzaakt.
