### ISSUE TITLE
eqsodus artwork

### ISSUE THREAD

**Issue by j-gfx** [XvBMC/repository.xvbmc#393]
your fork of exodus is using the original artwork. i am the creator of said artwork and i do not give permission for it to be used in any fork. 
i would appreciate if you could source new artwork for your fork.
thankyou

**Comment by OpenELEQ** [comment]
In both plugin.video.exodus and script.artwork GPL v3 is used. Also no mention of you as the creator of said artwork. I would advice you to use a different license if you want to make similar claims in the future. Furthermore, as you've used original movie posters for a lot of the icons, I doubt you could come even close to  making such claims without risking getting tangled in copyright issues yourself. Also, the addon is modded is such a way that you can't easily execute it normally and does not show up in the video-addon section so the artwork is never actually used/shown. That being said: I've replaced the fanart, icon and effective links to the original artwork. You're welcome.
